name: Python Lint and Coverage

on: 
    push:
      branches: [ dev ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint coverage requests
    
    - name: Run pylint
      run: |
        pylint **/*.py
      continue-on-error: true
    
    - name: Run tests with coverage
      run: |
        coverage run -m unittest discover tests
        coverage xml
        coverage report
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
    
    - name: Generate coverage badge
      uses: tj-actions/coverage-badge-py@v1.8
      with:
        output: .github/coverage.svg
    
    - name: Commit coverage badge
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: 'Update coverage badge'
        add: '.github/coverage.svg'
