name: Deploy to Naver Cloud

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Run tests
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)  # PYTHONPATH 설정

    - name: Login to NAVER Cloud Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.NCR_ENDPOINT }}
        username: ${{ secrets.NCR_ACCESS_KEY }}
        password: ${{ secrets.NCR_SECRET_KEY }}
    
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.NCR_ENDPOINT }}/tax_calculator:latest
    
    - name: Deploy to VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.NAVER_CLOUD_HOST }}
        username: ${{ secrets.NAVER_CLOUD_USERNAME }}
        password: ${{ secrets.NAVER_CLOUD_PASSWORD }}
        port: ${{ secrets.NCP_PORT }}
        script: |
          sudo docker login ${{ secrets.NCR_ENDPOINT }} -u ${{ secrets.NCR_ACCESS_KEY }} -p ${{ secrets.NCR_SECRET_KEY }}
          sudo docker stop tax_calculator || true
          sudo docker rm tax_calculator || true
          sudo docker pull ${{ secrets.NCR_ENDPOINT }}/tax_calculator:latest
          sudo docker run -d -p 8000:8000 --name tax_calculator ${{ secrets.NCR_ENDPOINT }}/tax_calculator:latest
